### ISSUE TITLE
请问 /src/utils/skin.ts 请干什么用的？

### ISSUE THREAD

**Issue by ColinCLL** [Maorey/vue-tpl#2]
https://github.com/Maorey/vue-tpl/blob/master/src/utils/skin.ts#L36-L123
请问这块代码是干什么用的，为什么loader中要用，同时这里也有

**Comment by Maorey** [comment]
该文件主要用于自定义皮肤切换事件以及处理方式, 现在是使用 `eventBus` 来订阅/发布换肤事件
默认导出函数用于自定义`CSS Object`处理函数, 即: `import style from '*.scss'` 得到的 `style` 为该函数的返回值. 该函数做了不同皮肤得到的`style`不一样时返回 `Vue.observable` 对象, 并且在切换皮肤时更新该对象的值的处理, 这样`Vue`组件就可以进行数据双向绑定(需要放到能收集依赖的地方), 并且最小化维护代码成本.
至于为什么不只放在 `loader` 中原因如下:
1. 使支持自定义换肤事件(比如: `addEventListener` & `dispatchEvent`)
2. 使支持特殊场景, 比如:
``` TypeScript
import getObj from '@/utils/skin'

import light from  '@/scss/someStyle.module.scss?skin=light'
import dark from '@/scss/otherStyle.module.scss?skin=dark'

// Vue computed/render/beforeCreate(this.STYLE = STYLE)/watch/data 中使用
const STYLE = getObj({light, dark})
```
