### ISSUE TITLE
建议insertPreload优化配置

### ISSUE THREAD

**Issue by kkkman22** [Maorey/vue-tpl#3]
insertPreload.js 在生产和开发环境下不同配置.现在开发环境下,
![image](https://user-images.githubusercontent.com/23480907/79041962-68f96e00-7c26-11ea-82ea-0dad5b3b6a58.png)
![image](https://user-images.githubusercontent.com/23480907/79041976-77478a00-7c26-11ea-9c50-1e0158f1c0bd.png)

**Comment by Maorey** [comment]
可以在development.config.js里给这个插件传个参数控制，noPreload & noPrefetch
